"""ipacconf - configure an Ultimarc I-PAC 2 (2015+) from Linux.

Standard library only. Talks to the board through /dev/hidraw via the
HIDIOCSOUTPUT ioctl, which is the same USB transaction WinIPAC uses
(SET_REPORT, output report id 3) but needs no libusb, no udev rules and no
detaching of the kernel HID driver. That makes it a straight scp onto a
Batocera box, whose root filesystem is read-only and has no pip.

    python3 ipacconf list                     # what is attached
    python3 ipacconf dump -o before.json      # read the board's config
    python3 ipacconf apply p.json --dry-run   # show the diff, write nothing
    python3 ipacconf apply p.json             # write it (backs up first)
    python3 ipacconf restore before.json      # byte-exact restore
    python3 ipacconf saved                    # list backups and presets
    python3 ipacconf monitor                  # name the pin behind a press
    python3 ipacconf serve                    # web UI on :8080

The modules, in dependency order - each may import the ones above it and
none of the ones below:

    version errors identity protocol firmware linux pins
      codes -> codec -> device -> checks -> profiles -> library
      inputs/  keymap -> events -> devices -> monitor
      web/     monitors -> service -> handler -> server
      cli

`web.service` holds every operation the UI performs and knows nothing about
HTTP; `web.handler` is the only module that touches a request. A different
front end reuses the service and replaces the handler.

Submodules import their siblings directly (`from .codec import ...`) and
never from this package, which is a one-way facade over them.

Protocol sources: katie-snow/Ultimarc-linux (C) and katie-snow/QtPyUltimarc
(Python). See README.md.
"""

from __future__ import annotations

from .version import __version__
from .errors import (
    DeviceError,
    ProtocolError,
)
from .identity import (
    IPAC2_MODES,
    KNOWN_2015_PRODUCTS,
    MODE_HOTKEYS,
    MODE_HOTKEY_CONFLICTS,
    MODE_KEYBOARD,
    PRODUCT_IPAC2,
    PRODUCT_PRE2015,
    PRODUCT_XINPUT,
    VENDOR_2015,
    VENDOR_PRE2015,
    VENDOR_XINPUT,
    board_mode,
    looks_ultimarc,
)
from .protocol import (
    CHUNK,
    CONFIG_SIZE,
    DEBOUNCE,
    HEADER_READ,
    HEADER_WRITE,
    MACRO_FIRST_CODE,
    MACRO_LAST_CODE,
    MACRO_MAX_COUNT,
    MACRO_MAX_SIZE,
    MACRO_START,
    REPORT_ID,
    SHIFT_BIT,
    WRITE_SIZE,
    WRITE_TAIL,
    XINPUT_BIT,
    deframe,
    write_frames,
)
from .firmware import (
    FIRMWARE_NOTES,
    config_interface_for,
    firmware_note,
    firmware_supports_gamepad,
    flash_write_blocked,
)
from .linux import (
    _IOC_READ,
    _IOC_WRITE,
    _ioc,
    _iow,
    _iowr,
    _read_sysfs,
)
from .pins import (
    PIN_ACTION_INDEX,
    PIN_GROUPS,
    PIN_ORDER,
    PIN_TABLE,
)
from .codes import (
    ALL_CODES,
    CODE_GROUPS,
    CODE_NAMES,
    DPAD_COUNT,
    DPAD_DIRECTIONS,
    DPAD_FIRST_CODE,
    DPAD_NAME,
    GAMEPAD_BUTTONS_CONFIRMED,
    GAMEPAD_COUNT,
    GAMEPAD_FIRST_CODE,
    GAMEPAD_PREFIXES,
    GAME_CODES,
    GAME_CODE_FIRST,
    GAME_CODE_LAST,
    KEY_CODES,
    MOUSE_CODES,
    NONE,
    P2_FIRST_CODE,
    PLAYER_BLOCK,
    SYSTEM_CODES,
    _fmt_byte,
    code_to_name,
    control_span,
    invert_first_wins,
    is_game_code,
    name_to_code,
)
from .codec import (
    _action_name,
    _debounce_name,
    _decode_macros,
    _encode_macros,
    _resolve,
    as_write_command,
    decode_config,
    describe_offset,
    diff_config,
    encode_config,
)
from .device import (
    Board,
    DeviceInfo,
    FakeBoard,
    config_candidates,
    find_devices,
    find_usb_boards,
    no_config_node_reason,
    open_board,
    select_device,
)
from .checks import (
    CHECKS,
    MODE_SELECT_PINS,
    _gamepad_warning,
    collect,
    config_kind,
    find,
    hotkey_warning,
    mode_switch_note,
    unconfirmed_code_warning,
    xinput_warning,
)
from .profiles import (
    MAME_KEYBOARD,
    backup_dir,
    default_config,
    load_profile,
    load_raw,
    raw_from_profile,
    write_backup,
)
from .library import (
    LABEL_MAX,
    PIN_FIELDS,
    PRESET_DIR,
    SAVED_LIMIT,
    _saved_entry,
    import_notes,
    list_saved,
    merge_profile,
    profile_changes,
    profile_firmware,
    resolve_saved,
    saved_dirs,
    set_label,
)
from .inputs.keymap import (
    ABS_HAT0X,
    BOARD_MODIFIER_FIRST,
    BOARD_PRIVATE_FIRST,
    BOARD_TO_LINUX,
    BTN_JOYSTICK,
    BTN_LAST,
    BTN_MOUSE,
    EVIOCGRAB_NR,
    EV_ABS,
    EV_KEY,
    EV_REL,
    EV_SYN,
    HID_MODIFIER_FIRST,
    INPUT_EVENT_FORMAT,
    INPUT_EVENT_SIZE,
    LINUX_TO_BOARD,
    LINUX_TO_BOARD_MEDIA,
    REL_X,
    USB_KBD_KEYCODE,
    _build_linux_to_board,
)
from .inputs.events import (
    event_action,
    parse_input_events,
    pins_for_action,
    player_block_first,
)
from .inputs.devices import (
    InputDevice,
    _ancestor_with,
    _node_index,
    find_input_devices,
)
from .inputs.monitor import (
    BaseMonitor,
    EVENT_BUFFER,
    EventStream,
    FakeInputMonitor,
    InputMonitor,
    _fake_device,
    open_monitor,
)
from .cli import (
    AXIS_NAMES,
    _add_device_args,
    _add_input_args,
    _print_device,
    build_parser,
    cmd_apply,
    cmd_dump,
    cmd_list,
    cmd_monitor,
    cmd_restore,
    cmd_saved,
    cmd_serve,
    main,
    monitor_line,
    read_profile_quietly,
)
from .web.monitors import (
    MonitorHolder,
    SSE_HEARTBEAT,
    sse_frame,
)
from .web.handler import _make_handler
from .web.server import (
    _lan_address,
    serve,
)

__all__ = [
    "ABS_HAT0X",
    "ALL_CODES",
    "AXIS_NAMES",
    "BOARD_MODIFIER_FIRST",
    "BOARD_PRIVATE_FIRST",
    "BOARD_TO_LINUX",
    "BTN_JOYSTICK",
    "BTN_LAST",
    "BTN_MOUSE",
    "BaseMonitor",
    "Board",
    "CHECKS",
    "CHUNK",
    "CODE_GROUPS",
    "CODE_NAMES",
    "CONFIG_SIZE",
    "DEBOUNCE",
    "DPAD_COUNT",
    "DPAD_DIRECTIONS",
    "DPAD_FIRST_CODE",
    "DPAD_NAME",
    "DeviceError",
    "DeviceInfo",
    "EVENT_BUFFER",
    "EVIOCGRAB_NR",
    "EV_ABS",
    "EV_KEY",
    "EV_REL",
    "EV_SYN",
    "EventStream",
    "FIRMWARE_NOTES",
    "FakeBoard",
    "FakeInputMonitor",
    "GAMEPAD_BUTTONS_CONFIRMED",
    "GAMEPAD_COUNT",
    "GAMEPAD_FIRST_CODE",
    "GAMEPAD_PREFIXES",
    "GAME_CODES",
    "GAME_CODE_FIRST",
    "GAME_CODE_LAST",
    "HEADER_READ",
    "HEADER_WRITE",
    "HID_MODIFIER_FIRST",
    "INPUT_EVENT_FORMAT",
    "INPUT_EVENT_SIZE",
    "IPAC2_MODES",
    "InputDevice",
    "InputMonitor",
    "KEY_CODES",
    "KNOWN_2015_PRODUCTS",
    "LABEL_MAX",
    "LINUX_TO_BOARD",
    "LINUX_TO_BOARD_MEDIA",
    "MACRO_FIRST_CODE",
    "MACRO_LAST_CODE",
    "MACRO_MAX_COUNT",
    "MACRO_MAX_SIZE",
    "MACRO_START",
    "MAME_KEYBOARD",
    "MODE_HOTKEYS",
    "MODE_HOTKEY_CONFLICTS",
    "MODE_KEYBOARD",
    "MODE_SELECT_PINS",
    "MOUSE_CODES",
    "MonitorHolder",
    "NONE",
    "P2_FIRST_CODE",
    "PIN_ACTION_INDEX",
    "PIN_FIELDS",
    "PIN_GROUPS",
    "PIN_ORDER",
    "PIN_TABLE",
    "PLAYER_BLOCK",
    "PRESET_DIR",
    "PRODUCT_IPAC2",
    "PRODUCT_PRE2015",
    "PRODUCT_XINPUT",
    "ProtocolError",
    "REL_X",
    "REPORT_ID",
    "SAVED_LIMIT",
    "SHIFT_BIT",
    "SSE_HEARTBEAT",
    "SYSTEM_CODES",
    "USB_KBD_KEYCODE",
    "VENDOR_2015",
    "VENDOR_PRE2015",
    "VENDOR_XINPUT",
    "WRITE_SIZE",
    "WRITE_TAIL",
    "XINPUT_BIT",
    "_IOC_READ",
    "_IOC_WRITE",
    "_action_name",
    "_add_device_args",
    "_add_input_args",
    "_ancestor_with",
    "_build_linux_to_board",
    "_debounce_name",
    "_decode_macros",
    "_encode_macros",
    "_fake_device",
    "_fmt_byte",
    "_gamepad_warning",
    "_ioc",
    "_iow",
    "_iowr",
    "_lan_address",
    "_make_handler",
    "_node_index",
    "_print_device",
    "_read_sysfs",
    "_resolve",
    "_saved_entry",
    "as_write_command",
    "backup_dir",
    "board_mode",
    "build_parser",
    "cmd_apply",
    "cmd_dump",
    "cmd_list",
    "cmd_monitor",
    "cmd_restore",
    "cmd_saved",
    "cmd_serve",
    "code_to_name",
    "collect",
    "config_candidates",
    "config_interface_for",
    "config_kind",
    "control_span",
    "decode_config",
    "default_config",
    "deframe",
    "describe_offset",
    "diff_config",
    "encode_config",
    "event_action",
    "find",
    "find_devices",
    "find_input_devices",
    "find_usb_boards",
    "firmware_note",
    "firmware_supports_gamepad",
    "flash_write_blocked",
    "hotkey_warning",
    "import_notes",
    "invert_first_wins",
    "is_game_code",
    "list_saved",
    "load_profile",
    "load_raw",
    "looks_ultimarc",
    "main",
    "merge_profile",
    "mode_switch_note",
    "monitor_line",
    "name_to_code",
    "no_config_node_reason",
    "open_board",
    "open_monitor",
    "parse_input_events",
    "pins_for_action",
    "player_block_first",
    "profile_changes",
    "profile_firmware",
    "raw_from_profile",
    "read_profile_quietly",
    "resolve_saved",
    "saved_dirs",
    "select_device",
    "serve",
    "set_label",
    "sse_frame",
    "unconfirmed_code_warning",
    "write_backup",
    "write_frames",
    "xinput_warning",
]
